name: flag
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 28.2
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      - name: build flag
        run: |
          make flag.bin
          mkdir build
          cp -v flag.bin build/
      - name: upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flag
          path: build/
